baseURL: 'https://balintmazzag.netlify.app'
theme: hugo-apero
languageCode: en
title: Balint Mazzag
author: Balint Mazzag
copyright: ''
googleAnalytics: 'G-JKQ4WH70T0'
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  favicon: /img/favicon.ico
  headingFontFamily: sans-serif
  logo: /img/bmazzag_hexagon.png
  mainSections:
    - blog
    - project
    - talk
  math:
    renderer: katex
  navallcaps: yes
  orgLocal: Anywhere
  orgName: RStudio
  sharing_image: /img/papillons.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/mbalint9901
    - icon: linkedin
      icon_pack: fab
      url: https://www.linkedin.com/in/mazzag-b%C3%A1lint-066b2b69/
    - icon: facebook-square
      icon_pack: fab
      url: https://www.facebook.com/balint.mazzag
    - icon: orcid
      icon_pack: ai
      url: http://orcid.org/0000-0003-2027-4044
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: forest
  twitter: apreshill
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: apreshill/apero
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 2
    - name: Contributors
      title: Contributors
      url: /contributors/
      weight: 3
  header:
    - name: About
      title: About Me
      url: /about/
      weight: 1
    # - name: Blog
    #   title: Blog
    #   url: /blog/
    #   weight: 2
    - name: Projects
      title: Project Portfolio
      url: /project/
      weight: 3
privacy:
  disqus:
    disable: yes
  googleAnalytics:
    anonymizeIP: no
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: yes
    simple: yes
  twitter:
    disable: yes
    enableDNT: yes
    simple: no
  vimeo:
    disable: yes
    enableDNT: yes
    simple: yes
  youtube:
    disable: yes
    privacyEnhanced: yes
